[package]
authors = ["Damian Jaworek <damianjaworek@outlook.com>"]
edition = "2018"
name = "sente"
version = "0.1.0"

[lib]
name = "sente"
path = "src/lib.rs"

[[bin]]
name = "sentec"
path = "src/main.rs"

[build-dependencies]
[build-dependencies.lalrpop]
features = ["lexer"]
version = "0.19"

[dependencies]
lalrpop-util = "0.19"
leb128 = "0.2"
regex = "1"
structopt = "0.3"
