[package]
name = "esprimo"
version = "0.1.0"
authors = ["Damian Jaworek <damianjaworek@outlook.com>"]
edition = "2018"

[lib]
name = "esprimo"
path = "src/lib.rs"

[[bin]]
name = "esprimoc"
path = "src/main.rs"

[build-dependencies.lalrpop]
version = "0.19"
features = ["lexer"]

[dependencies]
lalrpop-util = "0.19"
regex = "1"
structopt = "0.3"
