use crate::ast::{Expression, Operator, Number};

grammar;

pub Exprs: Vec<Box<Expression>> = (<Expr> ";")* => <>;

Expr: Box<Expression> = {
    Expr ExprOp Factor => Box::new(Expression::Operation(<>)),
    Factor,
};

ExprOp: Operator = {
    "+" => Operator::Add,
    "-" => Operator::Subtract,
}

Factor: Box<Expression> = {
    Factor FactorOp Term => Box::new(Expression::Operation(<>)),
    Term,
};

FactorOp: Operator = {
    "*" => Operator::Multiply,
    "/" => Operator::Divide,
};

Term: Box<Expression> = {
    Num => Box::new(Expression::Number(<>)),
    "(" <Expr> ")",
};

Num: Number = {
    r"[0-9]+" => Number::Integer(String::from(<>)),
    r"[0-9]+\.[0-9]+" => Number::Float(String::from(<>)),
};
